<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\ProductVersion.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget><AssemblyName>HidHide.DriverSetup</AssemblyName>
    <Version>$(HidHideProductVersion)</Version>
    <AssemblyVersion>$(HidHideProductVersion)</AssemblyVersion>
    <FileVersion>$(HidHideProductVersion)</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
    <Compile Include="../Installer/DriverFilters.cs" Link="DriverFilters.cs" />
  </ItemGroup>
</Project>
